### ISSUE TITLE
"context.ɵgetModuleContext is not a function" error when upgrading @envelop/graphql-modules from 7.1.3 to 9.1.0 and using graphql-jit

### ISSUE THREAD

**Issue by laurisvan** [graphql-hive/envelop#2877]
### Issue workflow progress

*Progress of the issue based on the**<br>*[*Contributor Workflow*](<https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow>)

- [ ] 1\. The issue provides a<br>   [minimal reproduction](<https://en.wikipedia.org/wiki/Minimal_reproducible_example>) available on<br>   [Stackblitz](<https://stackblitz.com/fork/node>).
  - *Please install the latest* `@envelop/*` packages that you are using.
  - *Please make sure the reproduction is as small as possible.*
- [ ] 2\. A failing test has been provided
- [ ] 3\. A local solution has been provided
- [ ] 4\. A pull request is pending review

---

**Describe the bug**

I first must apologise of not being able to provide an easy-to-reproduce example. Tracing down a bug based on this report alone is hard. What I am asking is educated guesses on what the problem might be - that might help me to create a reproducible example.

When upgrading our GraphQL stack npm packages to their latest revisions, I started seeing `context.ɵgetModuleContext is not a function` error thown by some of the resolvers. The error is thrown in some of our simplest globally scoped modules doing nothing special.

The problem might be specific to largish graphql stacks (we have some 40 modules with maybe 100+ root level resolvers) and using several envelop plugins together. The error is likely tied to using graphql-modules and graphql-jit together, as disabling graphql-jit hides the error.

I tried to trace which package upgrade might have caused the errors, and it appears that only upgrading @envelop/graphql-modules surfaced the problem.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior**

Error not thrown.

**Environment:**

* OS: Max OS/X 26.2 (also the same on Dockerized images)
* NodeJS: 24.1.1.
* `@envelop/*` versions:
  * `@envelop/core`: `5.2.3` (also repeats on 5.5.0)

For the sake of completeness, I attached below our whole dependencies in package.json causing the failure: Only upgrading `@envelop/graphql-modules": "^9.1.1"` and keeping the other packages as-is triggered the errors. Please note that the `"graphql-modules": "^3.1.1"` package is already recent one (I first thought that might be the problem, but it works fine); and that we are not using `@envelop/graphql-jit` as we us our own fork plugin with a slightly different caching strategy (but otherwise exactly the same). I just wanted to pinpoint these as they might look a bit odd.

Our whole dependency set:<br>  "dependencies": {<br>    "@authenio/samlify-node-xmllint": "^2.0.0",<br>    "@aws-sdk/client-lambda": "^3.825.0",<br>    "@aws-sdk/client-s3": "^3.825.0",<br>    "@aws-sdk/client-ses": "^3.825.0",<br>    "@aws-sdk/client-ssm": "^3.825.0",<br>    "@aws-sdk/credential-provider-node": "^3.825.0",<br>    "@aws-sdk/lib-storage": "^3.825.0",<br>    "@envelop/core": "^5.2.3",<br>    "@envelop/graphql-modules": "^9.1.1",<br>    "@envelop/prometheus": "^12.1.3",<br>    "@fastify/accepts": "^5.0.2",<br>    "@fastify/cors": "^11.0.1",<br>    "@fastify/formbody": "^8.0.2",<br>    "@fastify/websocket": "^11.0.1",<br>    "@graphql-tools/schema": "^10.0.23",<br>    "@graphql-tools/utils": "^10.8.6",<br>    "@resvg/resvg-wasm": "^2.6.2",<br>    "ajv": "^8.17.1",<br>    "ajv-errors": "^3.0.0",<br>    "ajv-formats": "^2.1.1",<br>    "ajv-keywords": "^5.1.0",<br>    "bullmq": "^1.91.1",<br>    "cron": "^4.3.1",<br>    "dataloader": "^2.2.3",<br>    "date-fns": "^2.30.0",<br>    "date-fns-tz": "^2.0.1",<br>    "db-errors": "^0.2.3",<br>    "exceljs": "^4.4.0",<br>    "fast-jwt": "^6.0.2",<br>    "fastify": "^5.7.3",<br>    "firebase-admin": "^13.6.0",<br>    "graphql": "^16.11.0",<br>    "graphql-fields": "^2.0.3",<br>    "graphql-helix": "^1.13.0",<br>    "graphql-jit": "^0.8.7",<br>    "graphql-modules": "^3.1.1",<br>    "graphql-resolve-batch": "^1.0.3",<br>    "graphql-scalars": "^1.24.2",<br>    "graphql-subscriptions": "^3.0.0",<br>    "graphql-tag": "^2.12.6",<br>    "graphql-ws": "^6.0.5",<br>    "hash-wasm": "^4.12.0",<br>    "html-to-text": "^9.0.5",<br>    "interval-promise": "^1.4.0",<br>    "inversify": "^7.5.2",<br>    "inversify-inject-decorators": "^3.1.0",<br>    "ioredis": "^5.0.6",<br>    "jwk-to-pem": "^2.0.7",<br>    "kafkajs": "^2.2.4",<br>    "knex": "^3.1.0",<br>    "lodash": "^4.17.23",<br>    "lru-cache": "^11.1.0",<br>    "luxon": "^3.6.1",<br>    "mathjs": "^14.5.2",<br>    "mem": "^8.1.1",<br>    "mercurius-upload": "^8.0.0",<br>    "micromark": "^2.11.4",<br>    "mnemonist": "^0.40.3",<br>    "mysql": "^2.18.1",<br>    "objection": "^3.1.5",<br>    "odata": "^2.0.1",<br>    "p-debounce": "^2.1.0",<br>    "p-map": "^3.0.0",<br>    "p-memoize": "4.0.1",<br>    "p-queue": "^6.6.2",<br>    "p-wait-for": "^3.2.0",<br>    "pg": "^8.16.0",<br>    "pg-boss": "^9.0.3",<br>    "pg-types": "^4.0.2",<br>    "prom-client": "^15.1.3",<br>    "pug": "^3.0.3",<br>    "rate-limiter-flexible": "^7.1.1",<br>    "redlock": "^4.2.0",<br>    "reflect-metadata": "^0.2.2",<br>    "regenerator-runtime": "^0.14.1",<br>    "rrule": "^2.6.4",<br>    "samlify": "^2.10.0",<br>    "string-hash-64": "^1.0.3",<br>    "svgo": "^3.3.2",<br>    "tedious": "^18.6.1",<br>    "ts-odata-client": "^2.0.2",<br>    "tslib": "^2.8.1",<br>    "uuid": "^11.1.0",<br>    "weak-lru-cache": "^1.2.2",<br>    "ws": "^8.18.2"<br>  }

**Additional context**

**Comment by ardatan** [comment]
Could you try changing the order of those two plugins?

**Comment by laurisvan** [comment]
> Could you try changing the order of those two plugins?

I moved graphql-modules after graphql-jit, and that indeed works!

In the graphql-jit plugin README the order of the jit was last in the plugin array (and the comment hinted that the other plugins should come prior the graphql-jit). I wonder if the queries will be properly JITed if I move graphql-modules after jit?

**Comment by laurisvan** [comment]
For future readers: We switched the order of plugins in our envelop configuration so that graphql-jit is listed before graphql-modules. This seems to fix the problem with no visible side effects.

Hence I am closing this issue. Thanks @ardatan!
